# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LnR', '0002_auto_20160617_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
