# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LnR', '0003_auto_20160620_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='ABC', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=1983),
            preserve_default=False,
        ),
    ]
